services:
  mongodb:
    image: mongo:7.0
    container_name: sale-mongodb-local
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  wiremock:
    image: wiremock/wiremock:3.9.1
    container_name: sale-wiremock-local
    restart: unless-stopped
    ports:
      - "8089:8080"

volumes:
  mongodb_data:
